<?php
/**
 * @file
 * webform_and_register_form.features.translations.inc
 */

/**
 * Implements hook_translations_defaults().
 */
function webform_and_register_form_translations_defaults() {
  $translations = array();
  $translations['be:field']['02bd92faa38aaa6cc0ea75e59937a1ef'] = array(
    'source' => 'author',
    'context' => 'field_author:knowledge_base:label',
    'location' => 'field:field_author:knowledge_base:label',
    'translation' => 'Аўтар',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['14ab92d067f6221c0447426a05b12967'] = array(
    'source' => 'Состоите в партиях/общественных объединения/НГО?',
    'context' => 'field_social:queeze:label',
    'location' => 'field:field_social:queeze:label',
    'translation' => 'З\'яўляецеся сябрам іншых арганізацый/партый/аб\'яднанняў?',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['1c3e2eda19432084cce1ffb16f559113'] = array(
    'source' => 'Open tag',
    'context' => 'field_open_tag:afishi:label',
    'location' => 'field:field_open_tag:afishi:label',
    'translation' => 'Тэгі',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['1fa0384358131420aad18850e9466d9e'] = array(
    'source' => 'Какие информационные ресурсы Вы читаете?',
    'context' => 'field_information:queeze:label',
    'location' => 'field:field_information:queeze:label',
    'translation' => 'Якія інфармацыйныя рэсурсы вы чытаеце?',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['24c9529c8c0e7e95d73704abec045a9b'] = array(
    'source' => 'Время, деньги, распространение информации, рисование, фотографирование, написание новостей, пение и пр.',
    'context' => 'field_useful:queeze:description',
    'location' => 'field:field_useful:queeze:description',
    'translation' => 'Час, грошы, распаўсюд інфармацыі, маляванне, фатаграфаванне, напісанне артыкулаў і г.д.',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['2a19198f7eea5ac1e0e5188e6d6e25d2'] = array(
    'source' => 'Если да, то какой?',
    'context' => 'field_expirience_2:queeze:label',
    'location' => 'field:field_expirience_2:queeze:label',
    'translation' => 'Калі так, то які?',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['2aafb5d05c69c44a3570cd1cccade631'] = array(
    'source' => 'Если не учитесь и не работаете, укажите, чем занимаетесь',
    'context' => 'field_occupation:queeze:description',
    'location' => 'field:field_occupation:queeze:description',
    'translation' => 'Калі не вучыцеся і не працуеце абазначце чым займаецеся.',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['3fa4a3002edc53a4987651d40989bdbb'] = array(
    'source' => 'Например, вести кружок, помогать в организации мероприятий, рисовать, расклеивать афиши и т.д',
    'context' => 'field_desire:queeze:description',
    'location' => 'field:field_desire:queeze:description',
    'translation' => 'Напрыклад, весці гурток, дапамагаць у агранізацыі мерапрыемтсваў, рабіць рэкламу, маляваць, распаўсюджваць афішы і г.д.',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['407bfa2b2d34e588cb1ebe2f2e3d0ebc'] = array(
    'source' => 'Ваше фото',
    'context' => 'field_photo:queeze:label',
    'location' => 'field:field_photo:queeze:label',
    'translation' => 'Ваш фатаздымак',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['458fd2263993edc30ee26d112afd34b7'] = array(
    'source' => 'Место учебы/работы',
    'context' => 'field_occupation:queeze:label',
    'location' => 'field:field_occupation:queeze:label',
    'translation' => 'Месца вучобы/працы',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['4b3e014140da9ebb451b72e8a3428024'] = array(
    'source' => 'Был ли опыт участия в общественной деятельности?',
    'context' => 'field_expirience:queeze:label',
    'location' => 'field:field_expirience:queeze:label',
    'translation' => 'Які ў вас вопыт грамадскай/палітычнай дзейнасці?',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['4c05ac1589cf0010c4d7414654fe58c1'] = array(
    'source' => 'Ваши увлечения',
    'context' => 'field_interests:queeze:label',
    'location' => 'field:field_interests:queeze:label',
    'translation' => 'Вашы захапленні',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['4cfcce7a152a084636e8792758d34e95'] = array(
    'source' => 'Main information sources',
    'context' => 'field_information:queeze:description',
    'location' => NULL,
    'translation' => 'Асноўныя крыніцы інфармацыі',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['505e9bda9e1e7753c67dce0704024c9e'] = array(
    'source' => 'Дата рождения',
    'context' => 'field_birth_date:queeze:label',
    'location' => 'field:field_birth_date:queeze:label',
    'translation' => 'Дата нараджэння',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['5c93310dd0291e121181e830cdda892e'] = array(
    'source' => 'Gallery',
    'context' => 'field_gallery:afishi:label',
    'location' => 'field:field_gallery:afishi:label',
    'translation' => 'Галерэя',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['5d49e67c23994596740b13e28c5bc2cd'] = array(
    'source' => 'Фамилия, имя, отчество',
    'context' => 'field_name:queeze:description',
    'location' => 'field:field_name:queeze:description',
    'translation' => 'Фамилия, имя, отчество',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['623a7fb59a4d4baf2eb38752d1bd157a'] = array(
    'source' => 'Ваш профиль в социальных сетях (VK, FB, TW, G+)',
    'context' => 'field__vk_fb_tw_g_:queeze:label',
    'location' => 'field:field__vk_fb_tw_g_:queeze:label',
    'translation' => 'Ваш рахунак у сацыяльных сетках (VK, FB, TW, G+) ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['6903eacd9e538a523acc77d5cd2c36a0'] = array(
    'source' => 'Вы хотите подписаться на рассылку Фаланстера?',
    'context' => 'field_subscribe:user:label',
    'location' => 'field:field_subscribe:user:label',
    'translation' => 'Вы жадаеца падпісацца на рассылку Фаланстэра?',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['6c02037b9694d6a3f5e5940debe3ec08'] = array(
    'source' => 'Чым вам цікава займацца ў Фаланстэры?',
    'context' => 'field_what_are_you_interested_to:user:label',
    'location' => 'field:field_what_are_you_interested_to:user:label',
    'translation' => 'Чым вам цікава займацца ў Фаланстэры?',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['80148fa5ada7bcd36bf3b351ee3ca3b0'] = array(
    'source' => 'Адрес',
    'context' => 'field_address:queeze:label',
    'location' => 'field:field_address:queeze:label',
    'translation' => 'Адрас',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['8c0419e24f6ab5fcb941bb299d6de12e'] = array(
    'source' => 'Knowledge_vocabrary',
    'context' => 'field_knowledge:knowledge_base:label',
    'location' => 'field:field_knowledge:knowledge_base:label',
    'translation' => 'Фармат',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['90b28a2accd8d987f6fa7f46dd24f4dc'] = array(
    'source' => 'Чем можете быть полезны Фаланстеру?',
    'context' => 'field_useful:queeze:label',
    'location' => 'field:field_useful:queeze:label',
    'translation' => 'Чым вы можаце быць карысны Фаланстэру?',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['a996e88e66d85eab1f86e44826b27a51'] = array(
    'source' => 'Мобильный телефон с кодом оператора',
    'context' => 'field_operator_code:queeze:description',
    'location' => 'field:field_operator_code:queeze:description',
    'translation' => 'з кодам аператара',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['d0cd2248137f1acac2e79777d856305e'] = array(
    'source' => 'Нет',
    'context' => 'field_expirience:#allowed_values:0',
    'location' => 'field:field_expirience:#allowed_values:0',
    'translation' => 'Не',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['e04af96afe53462f72f39331b209a810'] = array(
    'source' => 'Да',
    'context' => 'field_expirience:#allowed_values:1',
    'location' => 'field:field_expirience:#allowed_values:1',
    'translation' => 'Так',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['e4deee2b3010734b7929ad56cb0075a2'] = array(
    'source' => 'Да, подтверждаю подписку',
    'context' => 'field_subscribe:#allowed_values:1',
    'location' => 'field:field_subscribe:#allowed_values:1',
    'translation' => 'Так, пацвярджаю падпіску',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['ee83fd6777ccaaf5c72126534d1acb26'] = array(
    'source' => 'Important Info',
    'context' => 'field_related_node:gallery:label',
    'location' => 'field:field_related_node:gallery:label',
    'translation' => 'Важная інфармацыя',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['f018302454ef082d46b30d73874f67c6'] = array(
    'source' => 'Чем бы Вы хотели заниматься в Фаланстере?',
    'context' => 'field_desire:queeze:label',
    'location' => 'field:field_desire:queeze:label',
    'translation' => 'Чым бы вы хацелі займацца ў Фаланстэры?',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['f2a7e2cd05df59f9124997bd060121cd'] = array(
    'source' => 'Если да, то в каких?',
    'context' => 'field_social_2:queeze:label',
    'location' => 'field:field_social_2:queeze:label',
    'translation' => 'Калі так, то якіх?',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['fc382ea18745bfef816da4c603e51b79'] = array(
    'source' => 'Falanster_taxonomy',
    'context' => 'field_f_voc:knowledge_base:label',
    'location' => 'field:field_f_voc:knowledge_base:label',
    'translation' => 'Раздзел базы ведаў',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['fdd70bf5665be25986736d042c0df3c7'] = array(
    'source' => 'fivestar',
    'context' => 'field_fivestar:knowledge_base:label',
    'location' => 'field:field_fivestar:knowledge_base:label',
    'translation' => 'Рэйтынг',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['be:field']['ff525040b2a300378596affbfd06bb9b'] = array(
    'source' => 'Мобильный телефон',
    'context' => 'field_operator_code:queeze:label',
    'location' => 'field:field_operator_code:queeze:label',
    'translation' => 'Мабільны тэлефон',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['02bd92faa38aaa6cc0ea75e59937a1ef'] = array(
    'source' => 'author',
    'context' => 'field_author:knowledge_base:label',
    'location' => 'field:field_author:knowledge_base:label',
    'translation' => 'Автор',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['1c3e2eda19432084cce1ffb16f559113'] = array(
    'source' => 'Open tag',
    'context' => 'field_open_tag:afishi:label',
    'location' => 'field:field_open_tag:afishi:label',
    'translation' => 'Теги',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['2a19198f7eea5ac1e0e5188e6d6e25d2'] = array(
    'source' => 'Если да, то какой?',
    'context' => 'field_expirience_2:queeze:label',
    'location' => 'field:field_expirience_2:queeze:label',
    'translation' => 'Если да, то какой? ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['407bfa2b2d34e588cb1ebe2f2e3d0ebc'] = array(
    'source' => 'Ваше фото',
    'context' => 'field_photo:queeze:label',
    'location' => 'field:field_photo:queeze:label',
    'translation' => 'Ваше фото ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['4cfcce7a152a084636e8792758d34e95'] = array(
    'source' => 'Main information sources',
    'context' => 'field_information:queeze:description',
    'location' => NULL,
    'translation' => 'Основные источники информации',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['5c93310dd0291e121181e830cdda892e'] = array(
    'source' => 'Gallery',
    'context' => 'field_gallery:afishi:label',
    'location' => 'field:field_gallery:afishi:label',
    'translation' => 'Галерея',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['623a7fb59a4d4baf2eb38752d1bd157a'] = array(
    'source' => 'Ваш профиль в социальных сетях (VK, FB, TW, G+)',
    'context' => 'field__vk_fb_tw_g_:queeze:label',
    'location' => 'field:field__vk_fb_tw_g_:queeze:label',
    'translation' => 'Ваш профиль в социальных сетях (VK, FB, TW, G+) ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['6903eacd9e538a523acc77d5cd2c36a0'] = array(
    'source' => 'Вы хотите подписаться на рассылку Фаланстера?',
    'context' => 'field_subscribe:user:label',
    'location' => 'field:field_subscribe:user:label',
    'translation' => 'Вы хотите подписаться на рассылку Фаланстера?',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['6c02037b9694d6a3f5e5940debe3ec08'] = array(
    'source' => 'Чым вам цікава займацца ў Фаланстэры?',
    'context' => 'field_what_are_you_interested_to:user:label',
    'location' => 'field:field_what_are_you_interested_to:user:label',
    'translation' => 'Чем вам интересно заниматься в Фаланстере?',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['8c0419e24f6ab5fcb941bb299d6de12e'] = array(
    'source' => 'Knowledge_vocabrary',
    'context' => 'field_knowledge:knowledge_base:label',
    'location' => 'field:field_knowledge:knowledge_base:label',
    'translation' => 'Формат',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['d0cd2248137f1acac2e79777d856305e'] = array(
    'source' => 'Нет',
    'context' => 'field_expirience:#allowed_values:0',
    'location' => 'field:field_expirience:#allowed_values:0',
    'translation' => 'Нет',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['e04af96afe53462f72f39331b209a810'] = array(
    'source' => 'Да',
    'context' => 'field_expirience:#allowed_values:1',
    'location' => 'field:field_expirience:#allowed_values:1',
    'translation' => 'Да',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['e4deee2b3010734b7929ad56cb0075a2'] = array(
    'source' => 'Да, подтверждаю подписку',
    'context' => 'field_subscribe:#allowed_values:1',
    'location' => 'field:field_subscribe:#allowed_values:1',
    'translation' => 'Да, подтверждаю подписку',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['ee83fd6777ccaaf5c72126534d1acb26'] = array(
    'source' => 'Important Info',
    'context' => 'field_related_node:gallery:label',
    'location' => 'field:field_related_node:gallery:label',
    'translation' => 'Важная информация',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['f2a7e2cd05df59f9124997bd060121cd'] = array(
    'source' => 'Если да, то в каких?',
    'context' => 'field_social_2:queeze:label',
    'location' => 'field:field_social_2:queeze:label',
    'translation' => 'Если да, то в каких? ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['fc382ea18745bfef816da4c603e51b79'] = array(
    'source' => 'Falanster_taxonomy',
    'context' => 'field_f_voc:knowledge_base:label',
    'location' => 'field:field_f_voc:knowledge_base:label',
    'translation' => 'Раздел базы знаний',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ru:field']['fdd70bf5665be25986736d042c0df3c7'] = array(
    'source' => 'fivestar',
    'context' => 'field_fivestar:knowledge_base:label',
    'location' => 'field:field_fivestar:knowledge_base:label',
    'translation' => 'Рейтинг',
    'plid' => 0,
    'plural' => 0,
  );
  return $translations;
}
