<?php

/**
 * @file
 * Install, update and uninstall functions for the content_theme_debugger module.
 */
 

/**
 * Implements hook_install().
 */
function content_theme_debugger_install() {

  db_update('system')
    ->fields(array('weight' => 1000))
    ->condition('name', 'content_theme_debugger')
    ->condition('type', 'module')
    ->execute();
}


/**
 * Implements hook_uninstall().
 */
function content_theme_debugger_uninstall() {

  variable_del('content_theme_debugger_blacklist');
}
