<?php
/**
 * @file
 * task_scroll_to_top.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function task_scroll_to_top_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'scroll_to_top_bg_color_hover';
  $strongarm->value = '#777777';
  $export['scroll_to_top_bg_color_hover'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'scroll_to_top_bg_color_out';
  $strongarm->value = '#CCCCCC';
  $export['scroll_to_top_bg_color_out'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'scroll_to_top_display_text';
  $strongarm->value = 1;
  $export['scroll_to_top_display_text'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'scroll_to_top_enable_admin_theme';
  $strongarm->value = 1;
  $export['scroll_to_top_enable_admin_theme'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'scroll_to_top_label';
  $strongarm->value = 'Back to top';
  $export['scroll_to_top_label'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'scroll_to_top_position';
  $strongarm->value = '1';
  $export['scroll_to_top_position'] = $strongarm;

  return $export;
}
