<?php

/**
 * @file
 * APC Status module hooks.
 */

/**
 * Implements hook_menu().
 */
function apc_status_menu() {
  $items['admin/reports/status/apc'] = array(
    'title' => 'APC',
    'page callback' => 'apc_status_apc',
    'access arguments' => array('access apc status'),
    'type' => MENU_CALLBACK,
    'file' => 'apc_status.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function apc_status_permission() {
  return array(
    'access apc status' => array(
      'title' => t('Access APC status'),
      'description' => t('View and clear the Alternative PHP Cache opcode cache.'),
      'restrict access' => TRUE,
    ),
  );
}
