<?php

/**
 * @file
 * APC Status install-time module hooks.
 */

/**
 * Implements hook_requirements().
 */
function apc_status_requirements($phase) {
  $requirements = array();
  $t = get_t();

  if ($phase == 'runtime') {
    $requirements['apc_status'] = array(
      'title' => $t('APC'),
      'value' => l(function_exists('apc_cache_info') ? 'Enabled' : 'Disabled', 'admin/reports/status/apc'),
    );
  }

  return $requirements;
}
